-------------------------------------------------------------------------------
Test set: com.web.gearz.services.FilingServiceTest
-------------------------------------------------------------------------------
Tests run: 16, Failures: 1, Errors: 15, Skipped: 0, Time elapsed: 0.419 sec <<< FAILURE!
shouldConnectToLocal(com.web.gearz.services.FilingServiceTest)  Time elapsed: 0.322 sec  <<< FAILURE!
junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at junit.framework.Assert.assertTrue(Assert.java:27)
	at com.web.gearz.services.FilingServiceTest.shouldConnectToLocal(FilingServiceTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)

shouldConnectToLocal(com.web.gearz.services.FilingServiceTest)  Time elapsed: 0.324 sec  <<< ERROR!
com.mongodb.MongoException$Network: can't call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.drop(DBCollection.java:423)
	at com.web.gearz.services.FilingServiceTest.tearDown(FilingServiceTest.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:37)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn't connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 36 more

shouldAddNewObject(com.web.gearz.services.FilingServiceTest)  Time elapsed: 0.002 sec  <<< ERROR!
com.mongodb.MongoException$Network: can't call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.getCount(DBCollection.java:470)
	at com.mongodb.DBCollection.getCount(DBCollection.java:437)
	at com.web.gearz.services.FilingServiceTest.shouldAddNewObject(FilingServiceTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn't connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 39 more

shouldAddNewObject(com.web.gearz.services.FilingServiceTest)  Time elapsed: 0.003 sec  <<< ERROR!
com.mongodb.MongoException$Network: can't call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.drop(DBCollection.java:423)
	at com.web.gearz.services.FilingServiceTest.tearDown(FilingServiceTest.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:37)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn't connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 36 more

shouldUpdateExistingObject(com.web.gearz.services.FilingServiceTest)  Time elapsed: 0.002 sec  <<< ERROR!
com.mongodb.MongoException$Network: can't call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.getCount(DBCollection.java:470)
	at com.mongodb.DBCollection.getCount(DBCollection.java:437)
	at com.web.gearz.services.FilingServiceTest.shouldUpdateExistingObject(FilingServiceTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn't connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 39 more

shouldUpdateExistingObject(com.web.gearz.services.FilingServiceTest)  Time elapsed: 0.003 sec  <<< ERROR!
com.mongodb.MongoException$Network: can't call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.drop(DBCollection.java:423)
	at com.web.gearz.services.FilingServiceTest.tearDown(FilingServiceTest.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:37)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn't connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 36 more

shouldAddObject2(com.web.gearz.services.FilingServiceTest)  Time elapsed: 0.002 sec  <<< ERROR!
com.mongodb.MongoException$Network: can't call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.getCount(DBCollection.java:470)
	at com.mongodb.DBCollection.getCount(DBCollection.java:437)
	at com.web.gearz.services.FilingServiceTest.shouldAddObject2(FilingServiceTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn't connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 39 more

shouldAddObject2(com.web.gearz.services.FilingServiceTest)  Time elapsed: 0.003 sec  <<< ERROR!
com.mongodb.MongoException$Network: can't call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.drop(DBCollection.java:423)
	at com.web.gearz.services.FilingServiceTest.tearDown(FilingServiceTest.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:37)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn't connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 36 more

shouldAddObject3(com.web.gearz.services.FilingServiceTest)  Time elapsed: 0.002 sec  <<< ERROR!
com.mongodb.MongoException$Network: can't call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.getCount(DBCollection.java:470)
	at com.mongodb.DBCollection.getCount(DBCollection.java:437)
	at com.web.gearz.services.FilingServiceTest.shouldAddObject3(FilingServiceTest.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn't connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 39 more

shouldAddObject3(com.web.gearz.services.FilingServiceTest)  Time elapsed: 0.003 sec  <<< ERROR!
com.mongodb.MongoException$Network: can't call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.drop(DBCollection.java:423)
	at com.web.gearz.services.FilingServiceTest.tearDown(FilingServiceTest.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:37)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn't connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 36 more

shouldAddObject4(com.web.gearz.services.FilingServiceTest)  Time elapsed: 0.002 sec  <<< ERROR!
com.mongodb.MongoException$Network: can't call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.getCount(DBCollection.java:470)
	at com.mongodb.DBCollection.getCount(DBCollection.java:437)
	at com.web.gearz.services.FilingServiceTest.shouldAddObject4(FilingServiceTest.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn't connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 39 more

shouldAddObject4(com.web.gearz.services.FilingServiceTest)  Time elapsed: 0.003 sec  <<< ERROR!
com.mongodb.MongoException$Network: can't call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.drop(DBCollection.java:423)
	at com.web.gearz.services.FilingServiceTest.tearDown(FilingServiceTest.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:37)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn't connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 36 more

shouldRetrieveDefaultText(com.web.gearz.services.FilingServiceTest)  Time elapsed: 0.002 sec  <<< ERROR!
com.mongodb.MongoException$Network: can't call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.getCount(DBCollection.java:470)
	at com.mongodb.DBCursor.count(DBCursor.java:501)
	at com.web.gearz.services.FilingService.getContent(FilingService.java:82)
	at com.web.gearz.services.FilingServiceTest.shouldRetrieveDefaultText(FilingServiceTest.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn't connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 40 more

shouldRetrieveDefaultText(com.web.gearz.services.FilingServiceTest)  Time elapsed: 0.003 sec  <<< ERROR!
com.mongodb.MongoException$Network: can't call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.drop(DBCollection.java:423)
	at com.web.gearz.services.FilingServiceTest.tearDown(FilingServiceTest.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:37)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn't connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 36 more

shouldRetrieveStoredContent(com.web.gearz.services.FilingServiceTest)  Time elapsed: 0.002 sec  <<< ERROR!
com.mongodb.MongoException$Network: can't call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.getCount(DBCollection.java:470)
	at com.mongodb.DBCursor.count(DBCursor.java:501)
	at com.web.gearz.services.FilingService.storeContent(FilingService.java:63)
	at com.web.gearz.services.FilingServiceTest.shouldRetrieveStoredContent(FilingServiceTest.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn't connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 40 more

shouldRetrieveStoredContent(com.web.gearz.services.FilingServiceTest)  Time elapsed: 0.004 sec  <<< ERROR!
com.mongodb.MongoException$Network: can't call something
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:195)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:193)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:160)
	at com.mongodb.DBApiLayer.doQuery(DBApiLayer.java:67)
	at com.mongodb.DBApiLayer$MyCollection.find(DBApiLayer.java:310)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:321)
	at com.mongodb.DB.command(DB.java:115)
	at com.mongodb.DBCollection.drop(DBCollection.java:423)
	at com.web.gearz.services.FilingServiceTest.tearDown(FilingServiceTest.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:37)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.io.IOException: couldn't connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:150)
	at com.mongodb.DBPort.go(DBPort.java:72)
	at com.mongodb.DBPort.call(DBPort.java:60)
	at com.mongodb.DBTCPConnector._call(DBTCPConnector.java:171)
	... 36 more

